services:
  db:
    image: mysql:latest
    container_name: loopback4-app-db
    environment:
     MYSQL_USER: ${DB_USERNAME}
     MYSQL_PASSWORD: ${DB_PASSWORD}
     MYSQL_DATABASE: ${DB_NAME}
     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - loopback4-app-network

networks:
  loopback4-app-network:
    driver: bridge

volumes:
  db_data:
